### ISSUE TITLE
Var region sizes that aren't a power of 2.

### ISSUE THREAD

**Issue by Tsudico** [kow/imprudence#6]
I made a variable sized region for Aurora of 768x768. Upon trying to log into the region directly, multiple times, I would get to "Initializing World" before the viewer would exit unexpectedly.

Imprudence.log:
2011-02-17T22:40:10Z newview/llpatchvertexarray.cpp(137) : error
2011-02-17T22:40:10Z ERROR: LLPatchVertexArray::create: mRenderLevelp or mRenderStridep was NULL; we'd crash soon.

Imprudence.dmp:
## Dump Summary

Last Write Time:    2/17/2011 4:40:10 PM
Process Name:   astra.exe : C:\Program Files (x86)\AstraViewer\astra.exe
Process Architecture:   x86
Exception Code: 0xC0000005
Exception Information:  The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:   Not Present

**Comment by kow** [comment]
won't be supporting these for now
